name: shopapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  easy_localization: ^3.0.7+1

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  introduction_screen: ^3.1.17
  curved_navigation_bar: ^1.0.6
  clippy_flutter: ^2.0.0-nullsafety.1
  share_plus: ^10.1.4
  fluentui_system_icons: ^1.1.273
  flutter_svg: ^2.0.17
  animated_text_kit: ^4.2.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  smooth_page_indicator: ^1.2.1
  badges: ^3.1.2
  google_maps_flutter: ^2.12.0
  geolocator: ^13.0.4
  http: ^1.3.0
  page_transition: ^2.2.1
  google_fonts: ^6.2.1
  hovering: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#fefefe" # Use a soft light background (less harsh than pure white)
  image: assets/undraw_showing-support_ixfc.png

                  

  # android: true
  # ios: true

  # android_gravity: center
  # ios_content_mode: center

  # fullscreen: true  # Gives an immersive clean look

  
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

