// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// Platform  Firebase App Id
// web       1:856808754766:web:3fe7693d5a523fca99bd1f
// android   1:856808754766:android:d93c4d5d5bce54b399bd1f
// ios       1:856808754766:ios:e1c410f3d2c6994199bd1f
// macos     1:856808754766:ios:e1c410f3d2c6994199bd1f
// windows   1:856808754766:web:006208d04ea2500f99bd1f
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3A99icwxFekpBnTW3TQb2-XMv5OR3TFo',
    appId: '1:856808754766:web:3fe7693d5a523fca99bd1f',
    messagingSenderId: '856808754766',
    projectId: 'kurd-shop1',
    authDomain: 'kurd-shop1.firebaseapp.com',
    storageBucket: 'kurd-shop1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1VmsjrMz6NWQdqXg-7kLCmFqD19FktfQ',
    appId: '1:856808754766:android:d93c4d5d5bce54b399bd1f',
    messagingSenderId: '856808754766',
    projectId: 'kurd-shop1',
    storageBucket: 'kurd-shop1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSzhgraiUPxbZgh0oIj-u9oKreKEXQbw',
    appId: '1:856808754766:ios:e1c410f3d2c6994199bd1f',
    messagingSenderId: '856808754766',
    projectId: 'kurd-shop1',
    storageBucket: 'kurd-shop1.firebasestorage.app',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSzhgraiUPxbZgh0oIj-u9oKreKEXQbw',
    appId: '1:856808754766:ios:e1c410f3d2c6994199bd1f',
    messagingSenderId: '856808754766',
    projectId: 'kurd-shop1',
    storageBucket: 'kurd-shop1.firebasestorage.app',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3A99icwxFekpBnTW3TQb2-XMv5OR3TFo',
    appId: '1:856808754766:web:006208d04ea2500f99bd1f',
    messagingSenderId: '856808754766',
    projectId: 'kurd-shop1',
    authDomain: 'kurd-shop1.firebaseapp.com',
    storageBucket: 'kurd-shop1.firebasestorage.app',
  );
}
